spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto:
  thymeleaf:
    prefix: classpath:/templates/
  liquibase:
    change-log: classpath:changelog.xml